name: Android CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/android.yml
      - android/**
  pull_request:
    paths:
      - .github/workflows/android.yml
      - android/**

jobs:
  build_signed_debug_apk:
    name: Build and Sign App Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build with Gradle
        id: gradle_build_debug
        run: ./android/gradlew assembleDebug -p android

      - name: Sign APK
        id: sign_apk_debug
        uses: noriban/sign-android-release@v5
        with:
          releaseDirectory: android/app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload signed debug apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-signed
          path: ${{ steps.sign_apk_debug.outputs.signedReleaseFile }}
          
  send_release_apk:
    name: Send Low Summer Release APK
    runs-on: ubuntu-latest
    needs: build_signed_debug_apk
    steps:
      - name: Download signed release apk
        uses: actions/download-artifact@v4
        with:
          name: app-debug-signed

      - name: Send APK to Low Summer CI Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: -1002230892820
          token: ${{ secrets.TELEGRAM_SIMPLE_BOT_TOKEN }}
          format: markdown
          document: ${{ steps.download_release_apk.outputs.file_path }}
          disable_web_page_preview: false
          message: |
            *Build Success!*
            Repository: *${{ github.repository }}*
            Branch: *${{ github.ref_name }}*
            Type: release
            Commit message: `${{ github.event.head_commit.message }}`
            [Check the logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
