name: Android CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/android.yml
      - android/**
  pull_request:
    paths:
      - .github/workflows/android.yml
      - android/**

jobs:
  build_signed_release_apk:
    name: Build and Sign App Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build with Gradle
        id: gradle_build_release
        run: ./android/gradlew assembleRelease -p android

      - name: Sign APK
        id: sign_apk_release
        uses: noriban/sign-android-release@v5
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload signed release apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: ${{ steps.sign_apk_release.outputs.signedReleaseFile }}
          
  send_release_apk:
    name: Send Release APK
    runs-on: ubuntu-latest
    needs: build_signed_release_apk
    steps:
      - name: Download signed release apk
        uses: actions/download-artifact@v4
        with:
          name: app-release-signed

      - name: Send APK to Release Channel Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: -1002230892820
          token: ${{ secrets.TELEGRAM_SIMPLE_BOT_TOKEN }}
          format: markdown
          document: app-release-signed
          disable_web_page_preview: false
          message: |
            *Release Build Success!*
            Repository: *${{ github.repository }}*
            Branch: *${{ github.ref_name }}*
            Type: release
            Commit message: `${{ github.event.head_commit.message }}`
            [Check the logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
